Awesome es6
ikoote1/Awesome-books-ES6 pull request #1
Opened 2023-02-20 20:06 UTC by ikoote1

##All about Awesome-ES6 project:
- Created working environment with Linters.
- Created JS, HTML, CSS index files.
- Added elements for the website.
- Styled the website.
- Used ES6 syntax in Javascript

2023-02-20 22:29 UTC, Omar-Muhamad reviewed
# Invalid ❌

Hi @ikoote1,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

Your Code Review Request is marked as invalid for these reasons:

- [ ] You didn't document your work professionally:
   - Please add all essential sections of the Microverse readme template.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

2023-02-21 07:02 UTC, wayungi reviewed
Hi @ikoote1 , 
![image](https://user-images.githubusercontent.com/99656687/220082777-7a0e6a7f-854d-4e32-9c38-3b1eb3b090e4.png)

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ❌ 
 - [ ] As the previous reviewer suggested, please correctly fill in your README. When you copy and paste a README from an earlier project, please remember to edit it. You can begin removing the link to the loom video presentation as it is irrelevant for this project. Please work on your readme.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-02-21 08:04 UTC, bobb-Rob requested changes
## STATUS: CHANGES REQUIRED ♻️
Hi @ikoote1, 

Good job so far! 👏👏👏 
There are some issues that you still need to work on to go to the next project but you are almost there!  😃 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>
![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)

## Highlights
✅ No Linter error
✅ Correct use of GitHub flow
✅ Very descriptive Pull Request(PR)
✅ Neat Commit messages 

## Required Changes ♻️

- [ ] [OPTIONAL] Your commit messages can get even more better. Please read [this article](https://www.freecodecamp.org/news/writing-good-commit-messages-a-practical-guide/) to learn more.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-21 08:04 UTC, bobb-Rob commented on modules/date.js
> +}
- [x] You are expected to use `Arrow functions` instead of the legacy `function` keyword. Please refactor this function.

2023-02-21 08:04 UTC, bobb-Rob commented on modules/navigate.js
> +}
You are expected to use `Arrow functions` instead of the legacy `function` keyword. Please refactor this function.

2023-02-21 08:04 UTC, bobb-Rob commented on index.js
> +  }
- [ ] [OPTIONAL] Please consider navigating to the book list after a book is successfully added. Alternatively, you can display notifications, `success` or `failure` after a book is added `successfully` or `not added` respectively.  Currently, after the `add` button is clicked, nothing happens, so it is confusing if it was successful or not.

2023-02-21 09:42 UTC, prolajumokeoni approved these changes
Hi @ikoote1 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
 
 - App works properly 🚀  

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-21 09:59 UTC, merged